apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: webapp
  labels:
    app: myapp
    component: frontend
    color: blue
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31000
  selector:
    app: myapp
    component: frontend
    color: blue