apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: webapp
  labels:
    app: myapp
    component: frontend
    # version: {{APP_VERSION}}
    color: blue
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: myapp
    component: frontend
    # version: {{APP_VERSION}}
    color: blue
