apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-{{APP_COLOR}}
  namespace: webapp
  labels:
    app: employees
    component: frontend
    # version: {{APP_VERSION}}
    color: {{APP_COLOR}}
spec:
  selector:
    matchLabels:
      app: employees
      component: frontend
      # version: {{APP_VERSION}}
      color: {{APP_COLOR}}
  replicas: 1
  template:
    metadata:
      labels:
        app: employees
        component: frontend
        # version: {{APP_VERSION}}
        color: {{APP_COLOR}}
    spec:
      containers:
      - name: myapp-{{APP_COLOR}}
        image: 636276102612.dkr.ecr.us-east-1.amazonaws.com/app_image
        env:
        - name: DBHOST
          value: "mysql.sqldb.svc.cluster.local"
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mydb-secret
              key: password
        - name: APP_COLOR
          value: {{APP_COLOR}}
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi