apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-{{APP_COLOR}}
  namespace: webapp
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: mywebapp
    app.kubernetes.io/instance: myapp-{{APP_COLOR}}
    app.kubernetes.io/version: "v1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: myapp
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: mywebapp
      app.kubernetes.io/instance: myapp-{{APP_COLOR}}
      app.kubernetes.io/version: "v1"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: mywebapp
        app.kubernetes.io/instance: myapp-{{APP_COLOR}}
        app.kubernetes.io/version: "v1"
    spec:
      containers:
      - name: myapp-pod-{{APP_COLOR}}
        image: 636276102612.dkr.ecr.us-east-1.amazonaws.com/app_image
        env:
        - name: DBHOST
          value: "mysql-service.sqldb.svc.cluster.local"
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mydb-secret
              key: password
        - name: APP_COLOR
          value: {{APP_COLOR}}
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
