apiVersion: v1
kind: Service
metadata:
  name: myapp-{{APP_COLOR}}
  namespace: webapp
  labels:
    app: employees
    component: frontend
    # version: {{APP_VERSION}}
    color: {{APP_COLOR}}
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: employees
    component: frontend
    # version: {{APP_VERSION}}
    color: {{APP_COLOR}}
