apiVersion: v1
kind: Service
metadata:
  name: myapp-nodeport-{{APP_COLOR}}
  namespace: webapp
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: mywebapp
    app.kubernetes.io/instance: myapp-{{APP_COLOR}}
    app.kubernetes.io/version: "v1"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: {{APP_CONTAINER}}
  selector:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: mywebapp
    app.kubernetes.io/instance: myapp-{{APP_COLOR}}
    app.kubernetes.io/version: "v1"
