apiVersion: v1
kind: Service
metadata:
  name: myapp-{{APP_COLOR}}
  namespace: webapp
  labels:
    app: employees
    component: frontend
    color: {{APP_COLOR}}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: {{APP_CONTAINER}}
  selector:
    app: employees
    component: frontend
    color: {{APP_COLOR}}