{{- if .Values.shared.deploy }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  namespace: {{ .Values.metadata.namespace.frontend }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      {{- $root := . }}
      {{- $appName := .Values.app.name }}
      {{- $servicePort := .Values.ingress.servicePort }} 
      {{- range .Values.ingress.paths }}
      - path: {{ .path }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: "{{ $appName }}-{{ .name }}-svc"
            port:
              number: {{ $servicePort }}
      {{- end }}
{{- end }}